/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.LapTrinhTienTien.ui.Staff;

import java.awt.Component;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Admin
 */
public class PanelDate extends javax.swing.JPanel {

    private int month;
    private int year;

    public PanelDate(int month, int year) {
        initComponents();
        this.month = month;
        this.year = year;
        init();
    }

    private void init() {
        mon.asTitle();
        tue.asTitle();
        wed.asTitle();
        thu.asTitle();
        fri.asTitle();
        sat.asTitle();
        sun.asTitle();
        setDate();
    }
        private void setDate() {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month - 1);  //  month jan as 0 so start from 0
        calendar.set(Calendar.DATE, 1);
        int startDay = calendar.get(Calendar.DAY_OF_WEEK) - 1;  //  get day of week -1 to index
        calendar.add(Calendar.DATE, -startDay);
        ToDay toDay = getToDay();
        for (Component com : getComponents()) {
            Cell cell = (Cell) com;
            if (!cell.isTitle()) {
                cell.setText(calendar.get(Calendar.DATE) + "");
                cell.setDate(calendar.getTime());
                cell.currentMonth(calendar.get(Calendar.MONTH) == month - 1);
                if (toDay.isToDay(new ToDay(calendar.get(Calendar.DATE), calendar.get(Calendar.MONTH) + 1, calendar.get(Calendar.YEAR)))) {
                    cell.setAsToDay();
                }
                calendar.add(Calendar.DATE, 1); //  up 1 day
            }
        }
    }

    private ToDay getToDay() {
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        return new ToDay(calendar.get(Calendar.DATE), calendar.get(Calendar.MONTH) + 1, calendar.get(Calendar.YEAR));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sun = new org.LapTrinhTienTien.ui.Staff.Cell();
        mon = new org.LapTrinhTienTien.ui.Staff.Cell();
        tue = new org.LapTrinhTienTien.ui.Staff.Cell();
        wed = new org.LapTrinhTienTien.ui.Staff.Cell();
        thu = new org.LapTrinhTienTien.ui.Staff.Cell();
        fri = new org.LapTrinhTienTien.ui.Staff.Cell();
        sat = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell8 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell9 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell10 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell11 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell12 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell13 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell14 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell15 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell16 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell17 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell18 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell19 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell20 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell21 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell22 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell23 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell24 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell25 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell26 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell27 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell28 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell29 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell30 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell31 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell32 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell33 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell34 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell35 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell36 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell37 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell38 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell39 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell40 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell41 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell42 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell43 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell44 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell45 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell46 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell47 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell48 = new org.LapTrinhTienTien.ui.Staff.Cell();
        cell49 = new org.LapTrinhTienTien.ui.Staff.Cell();

        setLayout(new java.awt.GridLayout(7, 7));

        sun.setForeground(new java.awt.Color(241, 10, 10));
        sun.setText("Sun");
        add(sun);

        mon.setText("Mon");
        add(mon);

        tue.setText("Tue");
        add(tue);

        wed.setText("Wed");
        add(wed);

        thu.setText("Thu");
        add(thu);

        fri.setText("Fri");
        add(fri);

        sat.setText("Sat");
        add(sat);
        add(cell8);
        add(cell9);
        add(cell10);
        add(cell11);
        add(cell12);
        add(cell13);
        add(cell14);
        add(cell15);
        add(cell16);
        add(cell17);
        add(cell18);
        add(cell19);
        add(cell20);
        add(cell21);
        add(cell22);
        add(cell23);
        add(cell24);
        add(cell25);
        add(cell26);
        add(cell27);
        add(cell28);
        add(cell29);
        add(cell30);
        add(cell31);
        add(cell32);
        add(cell33);
        add(cell34);
        add(cell35);
        add(cell36);
        add(cell37);
        add(cell38);
        add(cell39);
        add(cell40);
        add(cell41);
        add(cell42);
        add(cell43);
        add(cell44);
        add(cell45);
        add(cell46);
        add(cell47);
        add(cell48);
        add(cell49);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.LapTrinhTienTien.ui.Staff.Cell cell10;
    private org.LapTrinhTienTien.ui.Staff.Cell cell11;
    private org.LapTrinhTienTien.ui.Staff.Cell cell12;
    private org.LapTrinhTienTien.ui.Staff.Cell cell13;
    private org.LapTrinhTienTien.ui.Staff.Cell cell14;
    private org.LapTrinhTienTien.ui.Staff.Cell cell15;
    private org.LapTrinhTienTien.ui.Staff.Cell cell16;
    private org.LapTrinhTienTien.ui.Staff.Cell cell17;
    private org.LapTrinhTienTien.ui.Staff.Cell cell18;
    private org.LapTrinhTienTien.ui.Staff.Cell cell19;
    private org.LapTrinhTienTien.ui.Staff.Cell cell20;
    private org.LapTrinhTienTien.ui.Staff.Cell cell21;
    private org.LapTrinhTienTien.ui.Staff.Cell cell22;
    private org.LapTrinhTienTien.ui.Staff.Cell cell23;
    private org.LapTrinhTienTien.ui.Staff.Cell cell24;
    private org.LapTrinhTienTien.ui.Staff.Cell cell25;
    private org.LapTrinhTienTien.ui.Staff.Cell cell26;
    private org.LapTrinhTienTien.ui.Staff.Cell cell27;
    private org.LapTrinhTienTien.ui.Staff.Cell cell28;
    private org.LapTrinhTienTien.ui.Staff.Cell cell29;
    private org.LapTrinhTienTien.ui.Staff.Cell cell30;
    private org.LapTrinhTienTien.ui.Staff.Cell cell31;
    private org.LapTrinhTienTien.ui.Staff.Cell cell32;
    private org.LapTrinhTienTien.ui.Staff.Cell cell33;
    private org.LapTrinhTienTien.ui.Staff.Cell cell34;
    private org.LapTrinhTienTien.ui.Staff.Cell cell35;
    private org.LapTrinhTienTien.ui.Staff.Cell cell36;
    private org.LapTrinhTienTien.ui.Staff.Cell cell37;
    private org.LapTrinhTienTien.ui.Staff.Cell cell38;
    private org.LapTrinhTienTien.ui.Staff.Cell cell39;
    private org.LapTrinhTienTien.ui.Staff.Cell cell40;
    private org.LapTrinhTienTien.ui.Staff.Cell cell41;
    private org.LapTrinhTienTien.ui.Staff.Cell cell42;
    private org.LapTrinhTienTien.ui.Staff.Cell cell43;
    private org.LapTrinhTienTien.ui.Staff.Cell cell44;
    private org.LapTrinhTienTien.ui.Staff.Cell cell45;
    private org.LapTrinhTienTien.ui.Staff.Cell cell46;
    private org.LapTrinhTienTien.ui.Staff.Cell cell47;
    private org.LapTrinhTienTien.ui.Staff.Cell cell48;
    private org.LapTrinhTienTien.ui.Staff.Cell cell49;
    private org.LapTrinhTienTien.ui.Staff.Cell cell8;
    private org.LapTrinhTienTien.ui.Staff.Cell cell9;
    private org.LapTrinhTienTien.ui.Staff.Cell fri;
    private org.LapTrinhTienTien.ui.Staff.Cell mon;
    private org.LapTrinhTienTien.ui.Staff.Cell sat;
    private org.LapTrinhTienTien.ui.Staff.Cell sun;
    private org.LapTrinhTienTien.ui.Staff.Cell thu;
    private org.LapTrinhTienTien.ui.Staff.Cell tue;
    private org.LapTrinhTienTien.ui.Staff.Cell wed;
    // End of variables declaration//GEN-END:variables
}
