/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.LapTrinhTienTien.ui.Staff;

import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import org.LapTrinhTienTien.StaticApp.Global;
import org.LapTrinhTienTien.model.CuaHang;
import org.LapTrinhTienTien.model.CuaHangSanPham;
import org.LapTrinhTienTien.model.GioHang;
import org.LapTrinhTienTien.model.IdClass.CuaHangSanPhamKey;
import org.LapTrinhTienTien.model.KhachHang;
import org.LapTrinhTienTien.model.SanPham;
import org.LapTrinhTienTien.repository.CuaHangSanPhamRepository;

import org.LapTrinhTienTien.repository.SanPhamRepository;
import org.LapTrinhTienTien.service.CuaHangSanPhamService;
import org.LapTrinhTienTien.service.SanPhamService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Controller;

/**
 *
 * @author Admin //chinh sua 5 image
 */
@Controller
public class WareHouseForm extends javax.swing.JPanel {
@Autowired
    SanPhamRepository sanPhamRepository;
    SanPhamService sanPhamService;
    CuaHangSanPhamRepository chspRepository;
    CuaHangSanPhamService shspService;
    public WareHouseForm(SanPhamRepository sanPhamRepository, CuaHangSanPhamRepository chspRepository) {
        initComponents();
        this.sanPhamRepository = sanPhamRepository;
        this.chspRepository = chspRepository;
        tf_maSP.setEditable(false);
        tf_tenSP.setEditable(false);
        tf_sl.setEditable(false);
        tf_donGia.setEditable(false);
        
    }
    public int laySL(SanPham sp)
    {
        CuaHangSanPham i = (CuaHangSanPham) sp.getCuaHangSanPham();
        int soLuong = i.getSoLuong();
        return soLuong;
    }
    public void loadDataToTable() {

        CuaHang cuaHang = Global.account.getNhanVien().getCuaHang();
        if (cuaHang != null)
        {
            List<SanPham> sanPhamList = new ArrayList<SanPham>();
        
            String maCH = cuaHang.getMaCH();
            System.out.println(maCH);
            List<CuaHangSanPham> cuaHangSanPhams = chspRepository.findAllByCuaHang(cuaHang);

            //Xoá bảng dữ liệu cũ
            DefaultTableModel model = (DefaultTableModel) tblSP.getModel();
            model.setRowCount(0);
            
            for (CuaHangSanPham chsp : cuaHangSanPhams) {
                if(chsp.getId().getCuaHangId().equals(maCH))
                {
                    SanPham sanPham = chsp.getSanPham();
                    //sanPhamList.add(sanPham);
                    model.addRow(new Object[]{
                        sanPham.getMaSP(),
                        sanPham.getTenSP(),
                        chsp.getSoLuong(),
                        sanPham.getTienThanhToan()
                    });
                    //System.out.println(chsp.getSoLuong());
                }
            }
        }else
        {
            System.out.print("null");
        }

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtSearchForm = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf_maSP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_tenSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_sl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_donGia = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbImage = new javax.swing.JLabel();

        jScrollPane1.setBorder(null);

        tblSP.setFont(new java.awt.Font("SF Pro Display", 0, 15)); // NOI18N
        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Đơn giá"
            }
        ));
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSP);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        txtSearchForm.setFont(new java.awt.Font("SF Pro Display", 0, 15)); // NOI18N

        btnSearch.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("SF Pro Display", 0, 13)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchForm, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchForm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã SP:");

        tf_maSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên SP:");

        tf_tenSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Số lượng:");

        tf_sl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Đơn giá:");

        tf_donGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbImage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_sl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_donGia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_tenSP, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_maSP))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tf_maSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_donGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        loadDataToTable();
        tf_maSP.setText("");
        tf_tenSP.setText("");
        tf_sl.setText("");
        tf_donGia.setText("");

    }//GEN-LAST:event_btnResetActionPerformed

    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseClicked
        int rowIndex = tblSP.getSelectedRow();
        String maSP = tblSP.getValueAt(rowIndex, 0).toString();
        String tenSP = tblSP.getValueAt(rowIndex, 1).toString();
        String soLuong = tblSP.getValueAt(rowIndex, 2).toString();
        String donGia = tblSP.getValueAt(rowIndex, 3).toString();
        tf_maSP.setText(maSP);
        tf_tenSP.setText(tenSP);
        tf_sl.setText(soLuong);
        tf_donGia.setText(donGia);
        
        //Load hình ảnh cho sản phầm
        SanPham sp = sanPhamRepository.findByMaSP(maSP);
        String imageResource = sp.getImage();
        if (imageResource != null)
        {
            ClassPathResource resource = new ClassPathResource(imageResource);
            try {
                Image image = ImageIO.read(resource.getInputStream());
                int width = 140;
                int height = 130;
                Image scaledImage = image.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(scaledImage);
                
                lbImage.setIcon(icon);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
    }//GEN-LAST:event_tblSPMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchText = txtSearchForm.getText();
        boolean containSP = searchText.contains("SP");
        CuaHang cuaHang = Global.account.getNhanVien().getCuaHang();
        
        //Xoá bảng dữ liệu cũ
        DefaultTableModel model = (DefaultTableModel) tblSP.getModel();
            model.setRowCount(0);
        
        if (containSP)
        {
            SanPham sanPham = sanPhamRepository.findByMaSP(searchText);      
            CuaHangSanPham chsp = chspRepository.findBySanPham_MaSPAndCuaHang_MaCH(searchText, cuaHang.getMaCH());
        
            model.addRow(new Object[]{
                sanPham.getMaSP(),
                sanPham.getTenSP(),
                chsp.getSoLuong(),
                sanPham.getTienThanhToan()
            });
        }
        else
        {
            searchText = searchText.toLowerCase();
            List<SanPham> sanPhamList = sanPhamRepository.findAll();
             for (SanPham sanPham : sanPhamList) 
             {
                if(sanPham.getTenSP().toLowerCase().contains(searchText))
                {
                    CuaHangSanPham chsp = chspRepository.findBySanPham_MaSPAndCuaHang_MaCH(sanPham.getMaSP(), cuaHang.getMaCH());
                    if (chsp !=null)
                    {
                        model.addRow(new Object[]{
                        sanPham.getMaSP(),
                        sanPham.getTenSP(),
                        chsp.getSoLuong(),
                        sanPham.getTienThanhToan()
                        });
                    }
                }
             }
        }

    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JTable tblSP;
    private javax.swing.JTextField tf_donGia;
    private javax.swing.JTextField tf_maSP;
    private javax.swing.JTextField tf_sl;
    private javax.swing.JTextField tf_tenSP;
    private javax.swing.JTextField txtSearchForm;
    // End of variables declaration//GEN-END:variables
}
